# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8080
    connection-timeout: 5000
    context-path: /blog

spring:
    #  dev|centos|pro
    profiles:
        active: centos
    # jackson
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    resources:
        static-locations: classpath:/static/,classpath:/views/

# Mybatis
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    configuration:
        map-underscore-to-camel-case: true


#\u65E5\u5FD7
#logging:
#  config: classpath:logback-${spring.profiles.active}.xml

#logging:
#  file: logs/application-debug.log
#  pattern:
#    console: "%d %-5level %logger : %msg%n"
#    file: "%d %-5level [%thread] %logger : %msg%n"
#  level:
#    org.springframework.web: ERROR
#    com.howtodoinjava: DEBUG
#    org.hibernate: ERROR

